export const translations = {
  en: {
    nav: { home: 'Home', services: 'Services', about: 'About', portfolio: 'Portfolio', process: 'Process', pricing: 'Pricing', contact: 'Contact' },
    hero: { badge: '✦ HELLO!', title: "I'm Lkhagvajav, a\nUI/UX designer.", sub: 'Creating meaningful digital experiences through thoughtful design and user-centered thinking.', cta: 'See My Works', available: 'I AM AVAILABLE · FOR FREELANCE · ' },
    portfolio: { label: '★ MY WORKS', title: 'Check out some of our awesome\nprojects with creative ideas.', seeAll: 'See All Works', viewCase: 'View Case Study', viewMore: 'VIEW\nMORE' },
    about: {
      label: '✦ ABOUT', title: 'More about me',
      bio1: "I'm Lkhagvajav, a UI/UX design student at UFE Tech and a certified Google UX Designer (Coursera).",
      bio2: "I've worked on multiple freelance app design gigs, front-end Flutter development at IO Tech (Artisy Hub project), and helped grow family businesses while managing my own creative projects. My journey blends both design and development, letting me craft experiences end-to-end.",
      moreCta: 'More About Me',
      expTitle: 'My experiences',
      expSub: "I've had the pleasure to work with diverse teams and industries, from tech to design to business. I'm always looking forward to exciting challenges that push my creativity and skills.",
      experience: [
        { period: 'JUN 2024 – SEP 2024', role: 'Flutter Front-End Developer (Artisy Hub)', place: 'IO Tech', color: '#3b3bff', desc: 'Worked on the front-end of the Artisy Hub mobile application using Flutter. Implemented nearly all core screens, focusing on functionality, responsiveness, and smooth performance. Took ownership of the majority of front-end development tasks though the project was not fully completed.' },
        { period: 'JAN 2024 – PRESENT', role: 'Google UX Design Certificate', place: 'Coursera', color: '#3b3bff', desc: "Completed Google's UX Design Professional Certificate, gaining practical training in design thinking, wireframing, prototyping, and user-centered design practices." },
        { period: 'MAY 2025 – PRESENT', role: 'UI/UX Design Student', place: 'UFE Tech', color: '#00c853', desc: 'Pursuing a degree in UI/UX design. Building skills in user research, prototyping, and product design while applying knowledge to real-world projects.' },
      ],
      stats: { customers: 'Satisfied happy customers', years: 'Years of work experience', projects: 'Successful projects done' }
    },
    process: { label: '✦ PROCESS', title: 'My workflow is centered around\nbeing highly productive.', tools: 'Tools that power my every day:', steps: [ { title: 'Research & Ideation', desc: 'Start by understanding your brand, audience, and goals gathering insights and sparking ideas that will shape the foundation of the design.' }, { title: 'Concept Development', desc: 'Translate insights into structured concepts and layout directions that align with your vision.' }, { title: 'Prototyping & Testing', desc: 'Build interactive prototypes and validate through user testing, then iterate based on real feedback.' }, { title: 'Finalize Product', desc: 'Polish every detail and deliver pixel-perfect, handoff-ready design files ready for development.' } ] },
    services: {
      label: '✦ SERVICES',
      title: 'What I can do\nfor you.',
      sub: 'From concept to shipping. I design and build digital products that look great and work even better.',
      items: [
        { title: 'UI/UX Design', desc: 'Intuitive interfaces backed by solid user research. Wireframes, prototypes, and pixel-perfect final screens.', tags: ['Figma', 'Framer', 'Prototyping'] },
        { title: 'Web Development', desc: 'Fast, accessible, and beautifully animated websites built with modern front-end technologies.', tags: ['React', 'Vite', 'Framer Motion'] },
        { title: 'Mobile Design', desc: 'Native and cross-platform mobile app design. From flow architecture to polished high-fidelity screens.', tags: ['Flutter', 'iOS', 'Android'] },
        { title: 'Brand Identity', desc: 'Visual systems that tell your story. Logo, color palette, typography, and guidelines your team will love using.', tags: ['Logo', 'Typography', 'Style Guide'] },
      ],
    },
    pricing: {
      label: '✦ PRICING',
      title: 'Simple, transparent\npricing.',
      sub: 'Pick the plan that fits your project. All plans include direct communication, revisions, and source files.',
      popular: '✦ MOST POPULAR',
      per: 'project',
      cta: 'Get Started',
      note: 'Have a bigger or custom project? Reach out via the contact form.',
      plans: [
        {
          name: 'Custom',
          tagline: 'Large-scale or ongoing design work.',
          priceText: 'Depends on the project',
          currency: '₮',
          featured: true,
          features: [
            'User research',
            'UI/UX design',
            'Web and mobile design',
            'Developer collaboration',
            'Research & user testing',
            'Design system & components',
            'Prototype and user flows',
            'Brand identity & visual direction',
            'Long-term collaboration available',
          ],
        },
      ],
    },
    contact: { label: '✦ CONTACT', title: "Got a project in mind?\nLet's get in touch.", name: 'Name', namePh: 'Your name', email: 'Email', emailPh: 'Email address', msg: 'Message', msgPh: 'Tell me about your project', submit: 'Submit', success: 'Opening your email client… Thanks!' },
    footer: { copy: '© Lhagva.' },
  },
  mn: {
    nav: { home: 'Нүүр', services: 'Үйлчилгээ', about: 'Миний тухай', portfolio: 'Портфолио', process: 'Процесс', pricing: 'Үнэ', contact: 'Холбоо барих' },
    hero: { badge: '✦ САЙН УУ!', title: "Намайг Лхагважав гэдэг,\nUI/UX дизайнер.", sub: 'Хэрэглэгч төвтэй сэтгэлгээгээр утга учиртай дижитал туршлага бүтээхийг зорьдог.', cta: 'Бүтээлүүдийг үзэх', available: 'БИ ЧӨЛӨӨТ АЖИЛД · БЭЛЭН · ' },
    portfolio: { label: '★ БҮТЭЭЛҮҮД', title: 'Хийсэн ажлуудаас', seeAll: 'Бүгдийг үзэх', viewCase: 'Дэлгэрэнгүй үзэх', viewMore: 'ҮЗЭХ' },
    about: {
      label: '✦ МИНИЙ ТУХАЙ', title: 'Дэлгэрэнгүй танилцуулга',
      bio1: 'Би Лхагважав, UFE Tech-д UI/UX дизайн судалж буй оюутан бөгөөд Google UX Дизайны гэрчилгээтэй (Coursera).',
      bio2: 'Олон чөлөөт дизайн ажил, IO Tech дахь Flutter хөгжүүлэлт (Artisy Hub), гэр бүлийн бизнесийн удирдлагын туршлагатай.',
      moreCta: 'Дэлгэрэнгүй',
      expTitle: 'Туршлага',
      expSub: 'Технологи, дизайн, бизнесийн салбарт баг, компанитай хамтран ажиллаж байсан.',
      experience: [
        { period: '2024 6-Р САР – 2024 9-Р САР', role: 'Flutter Front-End Хөгжүүлэгч (Artisy Hub)', place: 'IO Tech', color: '#3b3bff', desc: 'Artisy Hub мобайл аппликейшний фронт-энд дээр Flutter ашиглан ажилласан. Үндсэн дэлгэцүүдийн ихэнхийг хийж, функциональ байдал, responsive хариу үйлдэл, гүйцэтгэлд анхаарал хандуулсан. Төсөл бүрэн дуусаагүй ч фронт-энд хөгжүүлэлтийн ихэнх ажлыг хариуцаж байсан.' },
        { period: '2024 1-Р САР – ОДОО', role: 'Google UX Дизайн Гэрчилгээ', place: 'Coursera', color: '#3b3bff', desc: "Google-ийн UX Дизайны мэргэжлийн гэрчилгээг амжилттай дүүргэж, дизайн сэтгэлгээ, wireframing, прототип хийх, хэрэглэгч төвт дизайны практик мэдлэг олж авсан." },
        { period: '2025 5-Р САР – ОДОО', role: 'UI/UX Дизайны Оюутан', place: 'UFE Tech', color: '#00c853', desc: 'UFE Tech-д UI/UX дизайны чиглэлээр суралцаж байна. Хэрэглэгчийн судалгаа, прототип хийх, бүтээгдэхүүний дизайны чадвараа хөгжүүлж, бодит төслүүд дээр хэрэглэж байна.' },
      ],
      stats: { customers: 'Сэтгэл ханасан харилцагч', years: 'Ажлын туршлага (жил)', projects: 'Амжилттай дууссан төсөл' }
    },
    process: {
      label: '✦ ПРОЦЕСС',
      title: 'Миний ажлын арга барил\nбүтээмжид чиглэсэн.',
      tools: 'Өдөр тутам ашигладаг хэрэгслүүд:',
      steps: [
        { title: 'Research & Ideation', desc: 'Брэнд, үзэгчид, зорилгыг ойлгож дизайны үндэс суурийг тавина.' },
        { title: 'Concept Development', desc: 'Судалгааг бүтэцтэй concept болгон хувиргаж, таны алсын харааг тусгана.' },
        { title: 'Prototype & Test', desc: 'Interactive prototype бүтээж, user testing дээр үндэслэн сайжруулна.' },
        { title: 'Final Product', desc: 'Pixel-perfect дуусгаж, development-ready файлуудыг хүргэнэ.' },
      ],
    },
    services: {
      label: '✦ ҮЙЛЧИЛГЭЭ',
      title: 'Танд юу хийж\nчадах вэ.',
      sub: 'Санаанаас эхлэн хүргэлт хүртэл харагдахад гоё, ашиглахад хялбар дижитал бүтээгдэхүүн дизайнлаж, хөгжүүлдэг.',
      items: [
        { title: 'UI/UX Дизайн', desc: 'Хэрэглэгчийн судалгаанд тулгуурласан intuitive design. Wireframe, prototype, pixel-perfect screens.', tags: ['Figma', 'Framer', 'Prototype'] },
        { title: 'Web Development', desc: 'Орчин үеийн frontend технологиор хурдан, responsive, гоёмсог animation-тай вебсайт.', tags: ['React', 'Vite', 'Framer Motion'] },
        { title: 'Mobile Design', desc: 'Native болон cross-platform мобайл апп дизайн. User flow-аас high-fidelity дэлгэц хүртэл.', tags: ['Flutter', 'iOS', 'Android'] },
        { title: 'Branding', desc: 'Таны өгүүллэгийг илэрхийлэх visual system. Logo, color palette, typography, guidelines.', tags: ['Logo', 'Typography', 'Design System'] },
      ],
    },
    pricing: {
      label: '✦ ҮНЭ',
      title: 'Энгийн, тодорхой\nүнийн санал.',
      sub: 'Төсөлдөө тохирох багцыг сонго. Бүх багцад шууд харилцаа, засвар, эх файл багтана.',
      popular: '✦ ХАМГИЙН АЛДАРТАЙ',
      per: 'төсөл',
      cta: 'Эхлэх',
      note: 'Томоохон буюу захиалгат төсөл байна уу? Холбоо барих хэсгээр бичээрэй.',
      plans: [
        {
          name: 'Захиалгат',
          tagline: 'Том хэмжээний буюу тогтмол дизайн ажил.',
          priceText: 'Төслөөс хамаарч тохиролцоно',
          currency: '₮',
          featured: true,
          features: [
            'Хэрэглэгчийн судалгаа',
            'UI/UX дизайн',
            'Веб болон мобайл дизайн',
            'Хөгжүүлэгчтэй хамтарч ажиллах',
            'Судалгаа & хэрэглэгчийн тест',
            'Design system & component бэлдэх',
            'Prototype болон user flow',
            'Брэндийн өнгө төрх, visual direction',
            'Урт хугацааны хамтын ажиллагаа боломжтой',
          ],
        },
      ],
    },
    contact: { label: '✦ ХОЛБОО БАРИХ', title: "Төсөл санаа байна уу?\nХолбоо барицгаая.", name: 'Нэр', namePh: 'Таны нэр', email: 'Имэйл', emailPh: 'Имэйл хаяг', msg: 'Мэдэгдэл', msgPh: 'Төслийн талаар хэлэх', submit: 'Илгээх', success: 'Имэйл нээгдэж байна… Баярлалаа!' },
    footer: { copy: '© Лхагва.' },
  },
}
